// Generated by `python3 tools/version.py --write` from the repository's `VERSION` file.
//
// Do not edit this file: it is a **mirror** (`RELEASE.md` §1.3), and the authority is `VERSION`. Both
// `Package.swift` (at configure time) and `tools/version.py --check` (as a gate) refuse a disagreement,
// so editing the number here is how a wrong version ships.

/// The engine's version, so a user holding only the artifact can say what they are running
/// (`RELEASE.md` §1.3: identity is observable). `--version` on any of the tools prints it.
public enum TinyTitanVersion {
    public static let string = "1.0.0"
}
