#!/usr/bin/env python3
"""The version's single source of truth, and the mirrors that must agree with it.

`RELEASE.md` §1.3 says the version is **single-sourced and enforced**, not maintained by hope, and names
the shape of the enforcement: one authoritative file at the repository root, mirrors that a build or CI
refuses to disagree with, and a command that writes the mirrors from the authority. This is that command.

The authority is `VERSION` at the repository root. Its mirrors are *generated*: nothing here is
hand-maintained, so a bump is one edit plus one command

    $EDITOR VERSION && python3 tools/version.py --write

and `--check` is the gate that fails when a mirror drifts. `Package.swift` makes the same comparison at
configure time, so `swift build` refuses an inconsistent identity before it compiles anything.

**What is deliberately not a mirror.** The IR schema's `currentVersion` and the trace format's
`SCHEMA_VERSION` are separate axes — §1.3 is explicit that a schema version "must not be dragged along" —
so this file never touches them, and the semantic version of the product has nothing to say about the
version of a wire format.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AUTHORITY = "VERSION"
SEMANTIC = re.compile(r"^\d+\.\d+\.\d+$")

#: Mirror path -> the exact text it must contain. Generated, never edited by hand.
GENERATED_HEADER = """\
// Generated by `python3 tools/version.py --write` from the repository's `VERSION` file.
//
// Do not edit this file: it is a **mirror** (`RELEASE.md` §1.3), and the authority is `VERSION`. Both
// `Package.swift` (at configure time) and `tools/version.py --check` (as a gate) refuse a disagreement,
// so editing the number here is how a wrong version ships.
"""

VERSION_SWIFT = "sources/DatacenterEngine/Version.swift"


def render(version: str) -> dict[str, str]:
    """The exact contents every mirror must have for `version`."""
    return {
        VERSION_SWIFT: (
            GENERATED_HEADER
            + "\n/// The engine's version, so a user holding only the artifact can say what they are running\n"
            + "/// (`RELEASE.md` §1.3: identity is observable). `--version` on any of the tools prints it.\n"
            + "public enum TinyTitanVersion {\n"
            + f'    public static let string = "{version}"\n'
            + "}\n"
        )
    }


def read_authority(root: Path) -> str:
    path = root / AUTHORITY
    if not path.exists():
        raise SystemExit(f"{AUTHORITY} is missing at {root} — it is the version's single source of truth")
    return path.read_text(encoding="utf-8").strip()


def validate(version: str) -> None:
    """§1.3: one scheme, stated. `vX.Y.Z` as a tag, `X.Y.Z` in the authority."""
    if not SEMANTIC.match(version):
        raise SystemExit(
            f"{AUTHORITY} holds {version!r}; a semantic version is three dot-separated numbers, "
            "e.g. 1.0.0 — and no leading 'v' (the tag carries that)"
        )


def check(root: Path) -> int:
    version = read_authority(root)
    validate(version)
    problems: list[str] = []
    for relative, expected in render(version).items():
        path = root / relative
        actual = path.read_text(encoding="utf-8") if path.exists() else None
        if actual is None:
            problems.append(f"{relative} is missing; run `python3 tools/version.py --write`")
        elif actual != expected:
            problems.append(
                f"{relative} disagrees with {AUTHORITY} ({version}); "
                "run `python3 tools/version.py --write` rather than editing it"
            )
    if problems:
        for problem in problems:
            print(f"VERSION MISMATCH: {problem}", file=sys.stderr)
        return 1
    print(f"VERSION OK: {AUTHORITY} is {version} and {len(render(version))} mirror(s) agree")
    return 0


def write(root: Path) -> int:
    version = read_authority(root)
    validate(version)
    for relative, expected in render(version).items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8")
        print(f"wrote {relative}")
    return 0


def main(argv: list[str]) -> int:
    arguments = argv[1:]
    root = ROOT
    if "--root" in arguments:
        index = arguments.index("--root")
        if index + 1 >= len(arguments):
            raise SystemExit("--root needs a directory")
        root = Path(arguments[index + 1])
        del arguments[index : index + 2]
    if arguments == ["--check"]:
        return check(root)
    if arguments == ["--write"]:
        return write(root)
    if arguments == ["--print"]:
        version = read_authority(root)
        validate(version)
        print(version)
        return 0
    raise SystemExit("usage: version.py (--check | --write | --print) [--root DIR]")


if __name__ == "__main__":
    sys.exit(main(sys.argv))
